#include "types.h"

#define ATA_PORT_DATA 0x1F
#define ATA_PORT_ERROR 0x1F1
#define ATA_PORT_FEATURES 0x1F1
#define ATA_PORT_SECTOR_COUNT 0x1F2
#define ATA_PORT_LBA_LOW 0x1F3
#define ATA_PORT_LBA_MID 0x1F4
#define ATA_PORT_LBA_HIGH 0x1F5
#define ATA_PORT_DEVICE 0x1F6
#define ATA_PORT_COMMAND 0x1F7
#define ATA_PORT_STATUS 0x1F7

#define ATA_STATUS_BUSY 0x80
#define ATA_STATUS_DRQ 0x08
#define ATA_STATUS_ERR 0x01
